services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "2181:2181"
    networks:
      - mynetwork
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
    networks:
      - mynetwork
  event_dispatcher:
    build:
      context: ./
      dockerfile: EventDispatcher/Dockerfile
    container_name: event_dispatcher
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      KAFKA_BOOTSTRAPSERVERS: "localhost:9093"
    depends_on:
      - kafka
    ports:
      - "1984:1984"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
